### PR TITLE
Chronos: build yelp version with Mesos 1.0.1 libs and JDK 8

### PR DESCRIPTION
**Pull request by ko-be**
Testing new version of Chronos with Yelp fork of Chronos, Mesos 1.0.1 libs, JDK 8, Ubuntu 16.04 base docker image.

Was successfully able to build after making these changes.

```
docker build .

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:57 min
[INFO] Finished at: 2017-08-30T23:05:12+00:00
[INFO] Final Memory: 37M/283M
[INFO] ------------------------------------------------------------------------
 ---> 90d983b948f4
Removing intermediate container b549ff376768
Step 6/7 : EXPOSE 8080
 ---> Running in fa6d535db061
 ---> 855023fa02ce
Removing intermediate container fa6d535db061
Step 7/7 : ENTRYPOINT bin/start-chronos.bash
 ---> Running in 20bd7cda6a01
 ---> abeb386c677f
Removing intermediate container 20bd7cda6a01
Successfully built abeb386c677f

ko-be:chronos ko$ docker tag abeb386c677f behance/chronos:chronos-2.5.0-yelp31.ubuntu1404-mesos-1.0.1-2.0.93

ko-be:chronos ko$ docker push behance/chronos:chronos-2.5.0-yelp31.ubuntu1404-mesos-1.0.1-2.0.93
```

https://hub.docker.com/r/behance/chronos/tags/

EDIT: previous version didn't have the `/usr/bin/chronos` binary properly installed - not packaged correctly.

```
ko-be:chronos ko$ make docker-build
ko-be:chronos ko$ make docker-run-ubuntu-xenial

...

[INFO] Dependency-reduced POM written at: /work/dependency-reduced-pom.xml
[INFO] Dependency-reduced POM written at: /work/dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:42 min
[INFO] Finished at: 2017-08-31T21:28:27+00:00
[INFO] Final Memory: 73M/478M
[INFO] ------------------------------------------------------------------------
bin/build-distribution
bin/build-distribution: line 11: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
Concatenating
  bin/chronos-framework
  chronos/target/chronos-2.5.0-yelp31.jar
to form
  chronos-runnable.jar
mkdir -p "toor/ubuntu-xenial/usr/bin/"
cp chronos-runnable.jar "toor/ubuntu-xenial/usr/bin/chronos"
chmod 755 "toor/ubuntu-xenial/usr/bin/chronos"
mkdir -p "toor/ubuntu-xenial/etc/chronos/conf/"
echo 4400 > "toor/ubuntu-xenial/etc/chronos/conf/http_port"
fpm -C toor/ubuntu-xenial --iteration 1.ubuntu1604 \
	--after-install chronos.systemd.postinst \
	-t deb --config-files etc/ -d 'java8-runtime-headless | java7-runtime-headless | java6-runtime-headless' -d 'lsb-release' --after-install chronos.postinst --after-remove chronos.postrm -s dir -n chronos -v 2.5.0-yelp31 --architecture native --url "https://github.com/mesos/chronos" --license Apache-2.0 --description "Fault tolerant job scheduler for Mesos which handles dependencies and ISO8601 based schedules" --maintainer "Mesosphere Package Builder <support@mesosphere.io>" --vendor "Mesosphere, Inc." .
{:timestamp=>"2017-08-31T21:28:28.622167+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2017-08-31T21:28:30.272096+0000", :message=>"Created package", :path=>"chronos_2.5.0-yelp31-1.ubuntu1604_amd64.deb"}
ko-be:chronos ko$

ko-be:chronos ko$ ls -la dist
total 70096
drwxr-xr-x   4 ko  staff       136 Aug 31 14:28 .
drwxr-xr-x  25 ko  staff       850 Aug 31 14:28 ..
-rw-r--r--   1 ko  staff      1166 Aug 31 14:28 bintray.json
-rw-r--r--   1 ko  staff  35884178 Aug 31 14:28 chronos_2.5.0-yelp31-1.ubuntu1604_amd64.deb
```

### CODE REVIEW

**Comment by mannytoledo** [comment]
👍

**Comment by mannytoledo** [comment]
👍

**Comment by bossjones** [comment]
Awesome dude!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ko-be** [comment]
This is currently not yet working.

**Pull request closed without merging**
